# Etap 1: Budowanie aplikacji React
FROM node:18-alpine AS node-build 

WORKDIR /app

RUN apk add --no-cache git

# to do zrobić porywatne
RUN git clone https://github.com/PawRyng/AdminPanelStudyProject.git .

RUN npm install && npm run build

FROM nginx:alpine

COPY --from=node-build /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
