version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile-Admin_panel
    ports:
      - "80:80"  
    environment:
      - NODE_ENV=production  
    env_file:
      - .env  
    volumes:
      - .:/app  
    restart: always 
